project:
  type: website

website:
  title: "David Wu"
  favicon: images/favicon.png
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - bio.qmd
      - cv.qmd
      - blog.qmd

format:
  html:
    theme: 
      light: flatly 
      dark: cyborg
    css: styles.css
    toc: true

execute:
  freeze: true